### PR TITLE
Fix rounding issues in box buy in

### LINKED ISSUE #8: Some bug in buy-in margin calculations
reported by @Tuupertunut

### PR DESCRIPTION
**Pull request by Tuupertunut**
The box buy in form now displays product prices instead of box prices.
Fixes #8

### CODE REVIEW

**Comment by ArktinenKarpalo** [comment]
Should there be an option to alternatively input the price as box price?
For example typing 3.20b or b3.20 or just pressing b would change it such that box the price is used instead.

As sometimes only price of the box is known and using external methods of calculation to figure out price of a single item is a tedious task.

File: src/user_loop.rs [hunk 1]
```diff
@@ -377,9 +379,17 @@ fn buy_in_box(
             .expect("")
             .is_match(&input_line)
         {
-            buy_price = input_line.replace(".", "").parse().unwrap();
-            buy_price = (buy_price + (box_.items_per_box - 1)) / box_.items_per_box; // ceil
+            let box_buy_price = input_line.replace(".", "").parse::<i32>().unwrap();
+            buy_price = (box_buy_price as f64 / box_.items_per_box as f64).ceil() as i32;
```
Comment (Tuupertunut) [inline src/user_loop.rs:383]: This is equal to Rust's [i32::div_ceil](https://doc.rust-lang.org/std/primitive.i32.html#method.div_ceil), but that is still unstable.

**Comment by Tuupertunut** [comment]
> Should there be an option to alternatively input the price as box price?

That's what this is doing. You input the buy price for the whole box.
